version: '3.8'

services:
  setup:
    build:
      context: ..
      dockerfile: DevWorld.LaContessa.SetupJob/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Production
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - setup 