version: '3.3'

services:
  postgres:
    image: us-central1-docker.pkg.dev/lacontessa/lacontessa-be/postgres:v3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lacontessadb
      POSTGRES_PASSWORD: "lacontessa"
    volumes:
      - lacontessadb_data:/var/lib/postgresql/data
  setup:
    image: us-central1-docker.pkg.dev/lacontessa/lacontessa-be/setup:v3
    build:
      context: ..
      dockerfile: DevWorld.LaContessa.SetupJob/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Production
  app:
    image: us-central1-docker.pkg.dev/lacontessa/lacontessa-be/app:v3
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - setup 