version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443 
    depends_on:
      - postgres
  postgres:
    image: postgres:16.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lacontessadb
      POSTGRES_PASSWORD: "lacontessa"
    volumes:
      - lacontessadb_data:/var/lib/postgresql/data
volumes:
  lacontessadb_data:
