version: '3.8'

services:
  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lacontessadb
      POSTGRES_PASSWORD: "lacontessa"
    volumes:
      - lacontessadb_data:/var/lib/postgresql/data
  setup:
    build:
        context: .
        dockerfile: DevWorld.LaContessa.SetupJob/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
    depends_on:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
      - setup 
volumes:
  lacontessadb_data:
